// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NutriProj.Data;

#nullable disable

namespace NutriProj.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260418202710_AddUnitMealSlotRecipeCategory")]
    partial class AddUnitMealSlotRecipeCategory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("NutriProj.Models.Ingredient", b =>
                {
                    b.Property<int>("IdIng")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("CaloriesPer100g")
                        .HasColumnType("REAL");

                    b.Property<string>("NameIng")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("IdIng");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("NutriProj.Models.MealPlanner", b =>
                {
                    b.Property<int>("IdPlanner")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DailyCaloriesTarget")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdUser")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserIdUser")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("WeekStartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("IdPlanner");

                    b.HasIndex("UserIdUser");

                    b.ToTable("MealPlanners");
                });

            modelBuilder.Entity("NutriProj.Models.MealPlannerDetail", b =>
                {
                    b.Property<int>("IdDetail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Day")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdMealSlot")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdPlanner")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdRcp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MealPlannerIdPlanner")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MealSlotIdMealSlot")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecipeIdRcp")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdDetail");

                    b.HasIndex("MealPlannerIdPlanner");

                    b.HasIndex("MealSlotIdMealSlot");

                    b.HasIndex("RecipeIdRcp");

                    b.ToTable("MealPlannerDetails");
                });

            modelBuilder.Entity("NutriProj.Models.MealSlot", b =>
                {
                    b.Property<int>("IdMealSlot")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("IdMealSlot");

                    b.ToTable("MealSlots");
                });

            modelBuilder.Entity("NutriProj.Models.Recipe", b =>
                {
                    b.Property<int>("IdRcp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("RecipeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("TimeCooking")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimePreparation")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimeRest")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TypeKitchen")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdRcp");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("NutriProj.Models.RecipeCategory", b =>
                {
                    b.Property<int>("IdCategory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdMealSlot")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdRcp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MealSlotIdMealSlot")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecipeIdRcp")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdCategory");

                    b.HasIndex("MealSlotIdMealSlot");

                    b.HasIndex("RecipeIdRcp");

                    b.ToTable("RecipeCategories");
                });

            modelBuilder.Entity("NutriProj.Models.RecipeIngredient", b =>
                {
                    b.Property<int>("IdRecIng")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdIng")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdRcp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdUnit")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IngredientIdIng")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Quantity")
                        .HasColumnType("REAL");

                    b.Property<int>("RecipeIdRcp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnitIdUnit")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdRecIng");

                    b.HasIndex("IngredientIdIng");

                    b.HasIndex("RecipeIdRcp");

                    b.HasIndex("UnitIdUnit");

                    b.ToTable("RecipeIngredients");
                });

            modelBuilder.Entity("NutriProj.Models.Unit", b =>
                {
                    b.Property<int>("IdUnit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("GramEquivalent")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("IdUnit");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("NutriProj.Models.User", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("IdUser");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("NutriProj.Models.MealPlanner", b =>
                {
                    b.HasOne("NutriProj.Models.User", "User")
                        .WithMany("MealPlanners")
                        .HasForeignKey("UserIdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NutriProj.Models.MealPlannerDetail", b =>
                {
                    b.HasOne("NutriProj.Models.MealPlanner", "MealPlanner")
                        .WithMany("Details")
                        .HasForeignKey("MealPlannerIdPlanner")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NutriProj.Models.MealSlot", "MealSlot")
                        .WithMany()
                        .HasForeignKey("MealSlotIdMealSlot")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NutriProj.Models.Recipe", "Recipe")
                        .WithMany("MealPlannerDetails")
                        .HasForeignKey("RecipeIdRcp")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MealPlanner");

                    b.Navigation("MealSlot");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("NutriProj.Models.RecipeCategory", b =>
                {
                    b.HasOne("NutriProj.Models.MealSlot", "MealSlot")
                        .WithMany()
                        .HasForeignKey("MealSlotIdMealSlot")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NutriProj.Models.Recipe", "Recipe")
                        .WithMany("RecipeCategories")
                        .HasForeignKey("RecipeIdRcp")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MealSlot");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("NutriProj.Models.RecipeIngredient", b =>
                {
                    b.HasOne("NutriProj.Models.Ingredient", "Ingredient")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("IngredientIdIng")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NutriProj.Models.Recipe", "Recipe")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("RecipeIdRcp")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NutriProj.Models.Unit", "Unit")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("UnitIdUnit")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("NutriProj.Models.Ingredient", b =>
                {
                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("NutriProj.Models.MealPlanner", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("NutriProj.Models.Recipe", b =>
                {
                    b.Navigation("MealPlannerDetails");

                    b.Navigation("RecipeCategories");

                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("NutriProj.Models.Unit", b =>
                {
                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("NutriProj.Models.User", b =>
                {
                    b.Navigation("MealPlanners");
                });
#pragma warning restore 612, 618
        }
    }
}
